### ISSUE TITLE
replace 애니메이션 의견 제시

### ISSUE THREAD

**Issue by juyeong1260** [daangn/karrotframe#50]
# replace

첫번째가 아닌 페이지에서 replace 하면 화면이 새로 나와요 😭
혹시 이거를 조절 가능하게 할 수 있을까요?

## 첫번째가 아닌 페이지에서 `replace` 를 할 경우 

<img src="https://user-images.githubusercontent.com/12869255/111615192-c8430380-8823-11eb-97a5-0d15b361cbe1.gif" width="300" />

## 첫번째 페이지에서 `replace` 를 할 경우 

<img src="https://user-images.githubusercontent.com/12869255/111615167-c416e600-8823-11eb-8b50-c3ec14c1f1a6.gif" width="300" />

**Comment by tonyfromundefined** [comment]
replace의 animate: false 옵션을 활용하시면 됩니당!
