### ISSUE TITLE
Screen 컴포넌트 unmount 동작 관련 질문(+ 동적 라우팅)

### ISSUE THREAD

**Issue by woochanleee** [daangn/karrotframe#59]
# Screen 컴포넌트 unmount 동작 관련 질문(+ 동적 라우팅)

## 질문 하게 된 배경

토이 프로젝트를 진행하는 중에 로그인 여부에 따라 다른 컴포넌트를 라우팅 시키고 싶었습니다. 그래서 아래와 같이 코드를 작성했습니다:

```tsx
<Navigator
    theme="Cupertino"
    onClose={() => {
      window.alert('닫기 버튼이 눌렸습니다')
    }}
>
    {login ? (
      <Screen key="login" path="/" component={LoginHome} />
    ) : (
      <Screen key="home" path="/" component={Home} />
    )}
</Navigator>
```

## 문제점

제가 기대한 방식대로 동작하지 않았습니다. 왜 이렇게 동작하나 [Screen.tsx](https://github.com/daangn/karrotframe/blob/master/packages/karrotframe/src/navigator/Screen.tsx)를 살펴 보았는데, unmount 시 mobx store에 해당 스크린에 관한 정보를 제거해 주는 부분이 없습니다.

## 고민 해볼 점

아직 내부 코드를 다 이해하지 못 하였지만, "Screen 컴포넌트가 unmount시 store를 변경시킨다"를 구현하려면 꽤 고려해야 할 점 이 있다고 생각이 들었습니다. 예를 들어, 스크린 하나가 제거 된다면 순서가 꼬이게 되어 _si 또는 screenInstance.id 등의 값의 관계에 이슈가 있을 것 같다고 생각합니다.
위 고민에 대한 의견 또는 동적 라우팅을 구현하는(제 방식이 틀렸을 수도 있다고 생각합니다.) 다른 모범 사례가 있는지 여쭤보고 싶습니다!

감사합니다. ☺️

**Comment by tonyfromundefined** [comment]
0.16.0에 이슈 수정되어서 배포되었어요!
