### ISSUE TITLE
Depth보다 더 큰 값을 pop 할 때 발생하는 에러

### ISSUE THREAD

**Issue by jungpaeng** [daangn/karrotframe#63]
page depth가 0일 때 pop을 하거나, depth가 1일 때 pop(2)를 하는 등, depth보다 큰 값을 pop 하려 할 때 에러가 발생합니다.
이 부분에 대해서 depth가 0일 때 pop하려 하면 무시하고, depth보다 큰 값을 pop하려 하면 무시하는 코드가 추가되었으면 해요.

아래 코드에서 에러가 발생하고 있어요.
```
// useNavigator.ts in pop at line 96:5
// Cannot read property 'id' of undefined

const promise = store.screenInstancePromises.get(targetScreenInstance.id)
```

**Comment by tonyfromundefined** [comment]
0.16.0에 이슈 수정되어서 배포되었어요!
